/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bloddbank2;
    

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DonorLogin extends javax.swing.JFrame {
     Connection conn = null;
    PreparedStatement pst=null;
    ResultSet rs =null;
    /** Creates new form DonorLogin */
    public DonorLogin() {
        initComponents();
         this.setLocationRelativeTo(null);
        conn = connectjdbc.ConnecrDb();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jusernamefield = new javax.swing.JTextField();
        jpassfield = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Please Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 40, 160, 40);

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 51));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(280, 80, 220, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 220, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("User Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 160, 100, 30);

        jusernamefield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jusernamefield.setForeground(new java.awt.Color(255, 0, 0));
        jusernamefield.setText("UserName");
        jusernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusernamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(jusernamefield);
        jusernamefield.setBounds(320, 160, 220, 30);

        jpassfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jpassfield.setForeground(new java.awt.Color(255, 0, 0));
        jpassfield.setText("jPasswordField1");
        jpassfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassfieldActionPerformed(evt);
            }
        });
        jPanel1.add(jpassfield);
        jpassfield.setBounds(320, 220, 220, 30);

        loginbtn.setBackground(new java.awt.Color(0, 204, 0));
        loginbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("Login");
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
        });
        jPanel1.add(loginbtn);
        loginbtn.setBounds(440, 270, 100, 30);

        jSeparator2.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 350, 800, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("If you have not Signed up, Sign up here,,,");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(566, 390, 204, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Signup");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(720, 410, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Go Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 420, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wall5.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 794, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jusernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusernamefieldActionPerformed

    private void jpassfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassfieldActionPerformed

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
        // TODO add your handling code here:
         String query ="Select * from donor where DonorName=? and DonorPassword=?";
      try{
          pst = conn.prepareStatement(query);
          pst.setString(1,jusernamefield.getText());
          pst.setString(2,jpassfield.getText());
          rs = pst.executeQuery();
          if(rs.next()){
         //''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
         String msg1=jusernamefield.getText();
         String msg2=jpassfield.getText();
         //'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
        donorfield ns = new donorfield(msg1,msg2);
        ns.setVisible(true);
        ns.pack();
        ns.setLocationRelativeTo(null);
        ns.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
          }
          // Else e register re laganu lagbo*******************************************************************************************************************
             else{
              
              JOptionPane.showMessageDialog(null,"Access Denied ,Sign Up First ", "Invalid UserNamr or Password",JOptionPane.ERROR_MESSAGE);
          }
      
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_loginbtnMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        welcomepage hmm = new welcomepage();
        hmm.setVisible(true);
        hmm.pack();
        hmm.setLocationRelativeTo(null);
        hmm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonorLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jpassfield;
    private javax.swing.JTextField jusernamefield;
    private javax.swing.JButton loginbtn;
    // End of variables declaration//GEN-END:variables

}
