/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloddbank2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class donorfield extends javax.swing.JFrame {
 Connection conn = null;
    PreparedStatement pst=null;
    ResultSet rs =null;
    /**
     * Creates new form donorfield
     */
    public donorfield() {
        initComponents();
        
    }

   public  donorfield(String msg1, String msg2) {
        initComponents();
         this.setLocationRelativeTo(null);
        conn = connectjdbc.ConnecrDb();
      //  String query1 = ("SELECT * FROM donor Where DonorName=? and DonorPassword=?");
        
      /*   try{
          pst = conn.prepareStatement(query1);  
          pst.setString(1,msg1);
          pst.setString(2,msg2);
          rs = pst.executeQuery();
         datatable1.setModel(DbUtils.resultSetToTableModel(rs));
//'''''''''''''''''''''''''''''''''''''''''''''''''''''''
jnametag.setText(msg1);
//''''''''''''''''''''''''''''''''''''''''''''''''''   
      }
               catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }*/
      String query2=("SELECT DonorEmail from donor where DonorName=? and DonorPassword=?");   
          try{
          pst = conn.prepareStatement(query2);  
          pst.setString(1,msg1);
          pst.setString(2,msg2);

          rs = pst.executeQuery();
          jtable2.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      } 
          
          //'''''''''''''''''''''''''''''
          String query3=("SELECT DonationNo from donor where DonorName=? and DonorPassword=?");   
          try{
          pst = conn.prepareStatement(query3);  
          pst.setString(1,msg1);
          pst.setString(2,msg2);

          rs = pst.executeQuery();
          jtable3.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
          
           String query1 = ("SELECT * FROM donor Where DonorName=? and DonorPassword=?");
           try{
          pst = conn.prepareStatement(query1);  
          pst.setString(1,msg1);
          pst.setString(2,msg2);

          rs = pst.executeQuery();
          jTable2.setModel(DbUtils.resultSetToTableModel(rs));
          jnametag.setText(msg1);
          }
               catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jnametag = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jnametag.setFont(new java.awt.Font("Stencil Std", 0, 14)); // NOI18N
        jnametag.setForeground(new java.awt.Color(255, 96, 9));
        jnametag.setText("Name");
        jPanel1.add(jnametag, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 100, 20));

        jTable2.setBackground(new java.awt.Color(0, 204, 0));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        datatable1.setViewportView(jTable2);

        jScrollPane1.setViewportView(datatable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 890, 60));

        jtable2.setBackground(new java.awt.Color(102, 255, 102));
        jtable2.setFont(new java.awt.Font("Script MT Bold", 0, 13)); // NOI18N
        jtable2.setForeground(new java.awt.Color(0, 0, 153));
        jtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jtable2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 100, 180, 40));

        jtable3.setBackground(new java.awt.Color(0, 153, 0));
        jtable3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtable3.setForeground(new java.awt.Color(204, 0, 0));
        jtable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jtable3);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 11, 245));
        jLabel2.setText("Personal Profile");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("You Donation No is :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 130, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 60, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Club Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 90, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("You are now >>");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 110, 20));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Go Back");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 504, 70, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Do You want to update your information ?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 300, 20));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 204));
        jLabel10.setText("After Donating 5 times, You will enter in the presigious ELIT club :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 374, 380, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgwall.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable3MouseClicked
        // TODO add your handling code here:
        int i = jtable3.getSelectedRow();
        //System.out.println(i);
        TableModel model = jtable3.getModel();
        jLabel5.setText(model.getValueAt(i,0).toString());
        int aa = Integer.parseInt(jLabel5.getText().toString());
        System.out.println(aa);
        if(aa>5){
            jLabel6.setText("Elit Club");
        }
        else{
             jLabel6.setText("Good Member");
        }
    }//GEN-LAST:event_jtable3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        DonorLogin hmm = new DonorLogin();
        hmm.setVisible(true);
        hmm.pack();
        hmm.setLocationRelativeTo(null);
        hmm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        donorUpdate hmmm = new donorUpdate();
        hmmm.setVisible(true);
        hmmm.pack();
        hmmm.setLocationRelativeTo(null);
        hmmm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donorfield.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donorfield.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donorfield.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donorfield.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donorfield().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane datatable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jnametag;
    private javax.swing.JTable jtable2;
    private javax.swing.JTable jtable3;
    // End of variables declaration//GEN-END:variables
}
