/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloddbank2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SeekerLogin extends javax.swing.JFrame {
    
     Connection conn = null;
    PreparedStatement pst=null;
    ResultSet rs =null;

    /**
     * Creates new form SeekerLogin
     */
    public SeekerLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        conn = connectjdbc.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        signinbtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        signuplabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 11, 10));
        jLabel2.setText("Please Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 80, 170, 40);

        jSeparator1.setBackground(new java.awt.Color(255, 12, 14));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(260, 120, 210, 10);

        textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textfield.setForeground(new java.awt.Color(255, 0, 0));
        textfield.setText("username");
        jPanel1.add(textfield);
        textfield.setBounds(360, 180, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("User Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 180, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Password :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 250, 90, 30);

        passfield.setForeground(new java.awt.Color(255, 0, 0));
        passfield.setText("password");
        jPanel1.add(passfield);
        passfield.setBounds(360, 250, 210, 30);

        signinbtn.setBackground(new java.awt.Color(240, 30, 20));
        signinbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signinbtn.setForeground(new java.awt.Color(255, 255, 255));
        signinbtn.setText("Sign in");
        signinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn);
        signinbtn.setBounds(470, 300, 100, 40);

        jSeparator2.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 365, 780, 10);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("If you have not sign up, please sign up here,,,");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(530, 380, 230, 14);

        signuplabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signuplabel.setForeground(new java.awt.Color(255, 0, 0));
        signuplabel.setText("Sign Up");
        signuplabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signuplabelMouseClicked(evt);
            }
        });
        jPanel1.add(signuplabel);
        signuplabel.setBounds(694, 400, 60, 30);

        jLabel6.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("HOME");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 420, 60, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Go to");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 400, 50, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wall5.jpg"))); // NOI18N
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signuplabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplabelMouseClicked
        // TODO add your handling code here:
         seekerpad sp = new seekerpad();
        sp.setVisible(true);
        sp.pack();
        sp.setLocationRelativeTo(null);
        sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_signuplabelMouseClicked

    private void signinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtnActionPerformed
        // TODO add your handling code here:
         String query ="Select * from seeker where SeekerName=? and SeekerPassword=?";
      try{
          pst = conn.prepareStatement(query);
          pst.setString(1,textfield.getText());
          pst.setString(2,passfield.getText());
          rs = pst.executeQuery();
          if(rs.next()){
        seekerfield n = new seekerfield();
        n.setVisible(true);
        n.pack();
        n.setLocationRelativeTo(null);
        n.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
          }
          // Else e register re laganu lagbo*******************************************************************************************************************
             else{
              
              JOptionPane.showMessageDialog(null,"Access Denied ,Sign Up First ", "Invalid UserNamr or Password",JOptionPane.ERROR_MESSAGE);
          }
      
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
        
    }//GEN-LAST:event_signinbtnActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        welcomepage hmm = new welcomepage();
        hmm.setVisible(true);
        hmm.pack();
        hmm.setLocationRelativeTo(null);
        hmm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeekerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeekerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeekerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeekerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeekerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JButton signinbtn;
    private javax.swing.JLabel signuplabel;
    private javax.swing.JTextField textfield;
    // End of variables declaration//GEN-END:variables
}
