/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloddbank2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class seekerpad extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst=null;
    ResultSet rs =null;
    /**
     * Creates new form seekerpad
     */
    public seekerpad() {
        initComponents();
         this.setLocationRelativeTo(null);
        conn = connectjdbc.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jseekername = new javax.swing.JTextField();
        jseekeraddress = new javax.swing.JTextField();
        jseekercontact = new javax.swing.JTextField();
        jseekerid = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        submitbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Signup Here");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 10, 150, 50);

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(290, 60, 170, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 300, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Seeker Id :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 100, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("User Contact No :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 250, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("User Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 150, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("User Address :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 200, 110, 30);

        jseekername.setBackground(new java.awt.Color(204, 204, 204));
        jseekername.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jseekername.setForeground(new java.awt.Color(255, 0, 0));
        jseekername.setText("Give an User Name");
        jPanel1.add(jseekername);
        jseekername.setBounds(230, 150, 200, 30);

        jseekeraddress.setBackground(new java.awt.Color(204, 204, 204));
        jseekeraddress.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jseekeraddress.setForeground(new java.awt.Color(255, 0, 0));
        jseekeraddress.setText("Give Your Address");
        jPanel1.add(jseekeraddress);
        jseekeraddress.setBounds(230, 200, 200, 30);

        jseekercontact.setBackground(new java.awt.Color(204, 204, 204));
        jseekercontact.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jseekercontact.setForeground(new java.awt.Color(255, 0, 0));
        jseekercontact.setText("Give Your Contact No");
        jPanel1.add(jseekercontact);
        jseekercontact.setBounds(230, 250, 200, 30);

        jseekerid.setBackground(new java.awt.Color(204, 204, 204));
        jseekerid.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jseekerid.setForeground(new java.awt.Color(255, 0, 0));
        jseekerid.setText("Chose an Id");
        jseekerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jseekeridActionPerformed(evt);
            }
        });
        jPanel1.add(jseekerid);
        jseekerid.setBounds(230, 100, 200, 30);

        jpassword.setBackground(new java.awt.Color(204, 204, 204));
        jpassword.setForeground(new java.awt.Color(255, 0, 0));
        jpassword.setText("jPasswordField1");
        jPanel1.add(jpassword);
        jpassword.setBounds(230, 300, 200, 30);

        jSeparator2.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(480, 90, 10, 300);

        jSeparator3.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(468, 90, 10, 300);

        submitbtn.setBackground(new java.awt.Color(240, 25, 15));
        submitbtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("Submit");
        submitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitbtnMouseClicked(evt);
            }
        });
        jPanel1.add(submitbtn);
        submitbtn.setBounds(320, 350, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Go to Login page to sign in");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(610, 380, 160, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Sign in");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(710, 404, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wall5.jpg"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbtnMouseClicked
        // TODO add your handling code here:
         String query=("INSERT INTO seeker(SeekerId, SeekerName, SeekerAddress, SeekerPassword, SeekerContact) VALUES (?,?,?,?,?)");
        try{
           
            PreparedStatement pst = conn.prepareStatement(query);
           // pst=cn.prepareStatement(sql);
            pst.setString(1,jseekerid.getText());
            pst.setString(2,jseekername.getText());
            pst.setString(3,jseekeraddress.getText());
            pst.setString(4,jseekercontact.getText());
            pst.setString(5,jpassword.getText());
            pst.executeUpdate();
           ImageIcon img1 = new ImageIcon(getClass().getResource("/images/thumbsup.png"));
           JOptionPane.showMessageDialog(null, "SignUp Completed !","SignUp :",JOptionPane.INFORMATION_MESSAGE, img1);
        }
          catch(Exception e){
            
           JOptionPane.showMessageDialog(null, "SignUp Failed !" +e); 
        }
    }//GEN-LAST:event_submitbtnMouseClicked

    private void jseekeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jseekeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jseekeridActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
 SeekerLogin sp = new SeekerLogin();
        sp.setVisible(true);
        sp.pack();
        sp.setLocationRelativeTo(null);
        sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seekerpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seekerpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seekerpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seekerpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seekerpad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jseekeraddress;
    private javax.swing.JTextField jseekercontact;
    private javax.swing.JTextField jseekerid;
    private javax.swing.JTextField jseekername;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
